### PR TITLE
remove unused property ``computedReceivers``

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Did you plan to do something with this property ?

### CODE REVIEW

**Comment by eric-chau** [comment]
I Really don't get why Insight said that this attribute is not used cause I use it in `::addReceiver()` and `::buildEventReceivers()` TT

**Comment by eric-chau** [comment]
And as you can see travis is on error now.

**Comment by mickaelandrieu** [comment]
yeah :/ Insight is more and more buggy -_- too bad! Sorry for this useless pull request xD wanted to help ;)

**Comment by eric-chau** [comment]
Don't worry it's okay =) thank you for that ^^

**Pull request closed without merging**
